baseURL = "https://sue886.github.io/"
languageCode = "zh-cn"
title = "Zhl's Blog"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
env = "production"
title = "Zhl's Blog"
description = "ME"
keywords = ["Blog", "ML", "Life", "AI"]
author = "Zh"

# Outlook of the theme
defaultTheme = "auto"
disableThemeToggle = false

# functions of blog
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
math = true

# first page
homeInfoParams = { 
  Title = "welcome to Zhl's Blog ðŸ‘‹", 
  Content = "It's myblog" 
}

# assign parts
[params.homepage]
showCards = true
cardsLayout = "grid"
showCategories = true
showTags = true

# word
fontSans = "Inter, Helvetica, Arial, sans-serif"
fontMono = "Fira Code, monospace"

# search
disableSearch = false

# the book of blog 
ShowPostCover = true
ShowCover = true
cover = { hiddenInSingle = false, hiddenInList = false }

# search line
[menu]
[[menu.main]]
identifier = "tech"
name = "tech"
url = "/tech/"
weight = 1

[[menu.main]]
identifier = "life"
name = "life"
url = "/life/"
weight = 2

# code light
[markup]
[markup.highlight]
noClasses = false
style = "monokai"

[markup.goldmark.renderer]
unsafe = true

# communicate
[params.socialIcons]
[[params.socialIcons]]
name = "github"
url = "https://github.com/sue886"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"


[deployment]
order = [".jpg", ".png", ".gif", ".css", ".js"]

[[deployment.targets]]
name = "github"
URL = "git@github.com:Sue886/sue886.github.io.git"
branch = "main"
