baseURL = "https://sue886.github.io/"
languageCode = "zh-cn"
title = "Zhl's Blog"
theme = "PaperMod"

[params]
author = "Zh"
description = "ME"
keywords = ["Blog", "ML", "Life", "AI"]

homeInfoParams_title = "welcome to Zhl's Blog"
homeInfoParams_content = "It's myblog"

customCSS = ["css/custom.css"]

[menu]
[[menu.main]]
identifier = "tech"
name = "tech"
url = "/tech/"
weight = 1

[[menu.main]]
identifier = "life"
name = "life"
url = "/life/"
weight = 2

[markup]
[markup.highlight]
noClasses = false
style = "monokai"

[markup.goldmark.renderer]
unsafe = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/sue886"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[deployment]
order = [".jpg", ".png", ".gif", ".css", ".js"]

[[deployment.targets]]
name = "github"
url = "git@github.com:Sue886/sue886.github.io.git"
branch = "main"
